// Generated by CoffeeScript 1.10.0
var _, config, dirs, esprima, filter_dependencies, fs, fsu, path, resolve;

fs = require('fs');

path = require('path');

_ = require('lodash');

esprima = require('esprima');

fsu = require('fs-util');

dirs = require('../utils/dirs');

config = require('../utils/config');

resolve = require('./resolve');

exports.dependencies = function(filepath, raw) {
  var aliased, dep, i, len, ref;
  aliased = {};
  ref = filter_dependencies(esprima.parse(raw));
  for (i = 0, len = ref.length; i < len; i++) {
    dep = ref[i];
    aliased[dep] = resolve(filepath, dep);
  }
  return aliased;
};

exports.dependents = function(file, filepath, raw) {
  var dirpath, files, i, j, len, len1, ref, ref1;
  files = [];
  ref = config.input;
  for (i = 0, len = ref.length; i < len; i++) {
    dirpath = ref[i];
    ref1 = fsu.find(dirpath, file.compiler.ext);
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      filepath = ref1[j];
      if (filepath === file.filepath) {
        continue;
      }
      files.push({
        filepath: filepath,
        raw: fs.readFileSync(filepath).toString()
      });
    }
  }
  return file.compiler.resolve_dependents(file.filepath, files);
};

filter_dependencies = function(node, found) {
  var i, is_exp, is_idf, is_lit, is_req, item, key, len, ref, ref1, ref2, ref3;
  if (found == null) {
    found = [];
  }
  if (node instanceof Array) {
    for (i = 0, len = node.length; i < len; i++) {
      item = node[i];
      filter_dependencies(item, found);
    }
  } else if (node instanceof Object) {
    for (key in node) {
      item = node[key];
      filter_dependencies(item, found);
    }
  }
  if (node instanceof Object) {
    is_exp = (node != null ? node.type : void 0) === 'CallExpression';
    is_idf = (node != null ? (ref = node.callee) != null ? ref.type : void 0 : void 0) === 'Identifier';
    is_req = (node != null ? (ref1 = node.callee) != null ? ref1.name : void 0 : void 0) === 'require';
    is_lit = (node != null ? (ref2 = node["arguments"]) != null ? (ref3 = ref2[0]) != null ? ref3.type : void 0 : void 0 : void 0) === 'Literal';
    if (is_exp && is_idf && is_req && is_lit) {
      found.push(node["arguments"][0].value);
    }
  }
  return found;
};

//# sourceMappingURL=scan.js.map
