// Generated by CoffeeScript 1.10.0
var File, Files, _, argv, compiler, components, config, debug, dirs, error, fs, fsu, info, log_changed, log_created, log_deleted, logger, path, plugins, upath, warn,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

path = require('path');

upath = require('upath');

fs = require('fs');

fsu = require('fs-util');

_ = require('lodash');

dirs = require('../utils/dirs');

config = require('../utils/config');

compiler = require('./compiler');

argv = require('../cli').argv;

plugins = require('../utils/plugins');

logger = require('../utils/logger')('core/files');

components = require('../extras/component');

error = logger.error, warn = logger.warn, info = logger.info, debug = logger.debug;

log_created = logger.file.created;

log_changed = logger.file.changed;

log_deleted = logger.file.deleted;

File = require('./file');

module.exports = new (Files = (function() {
  var exts, plugin;

  exts = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = plugins.length; i < len; i++) {
      plugin = plugins[i];
      results.push(plugin.ext);
    }
    return results;
  })();

  Files.prototype.files = null;

  Files.prototype.watchers = null;

  function Files() {
    this.onfschange = bind(this.onfschange, this);
    this.refresh_dependents = bind(this.refresh_dependents, this);
    this.bulk_create_file = bind(this.bulk_create_file, this);
    this.watchers = [];
    this.collect();
  }

  Files.prototype.collect = function() {
    var dirpath, filepath, i, j, k, len, len1, len2, ref, ref1;
    this.files = [];
    ref = config.input;
    for (i = 0, len = ref.length; i < len; i++) {
      dirpath = ref[i];
      ref1 = fsu.find(dirpath, exts);
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        filepath = ref1[j];
        this.create_file(filepath);
      }
    }
    for (k = 0, len2 = components.length; k < len2; k++) {
      filepath = components[k];
      this.create_file(filepath);
    }
    if (argv.watch) {
      return this.watch_inputs();
    }
  };

  Files.prototype.create_file = function(filepath) {
    var file;
    if (filepath !== path.resolve(filepath)) {
      return;
    }
    if (file = _.find(this.files, {
      filepath: filepath
    })) {
      return file;
    }
    this.files.push(file = new File(filepath));
    file.on('new:dependencies', this.bulk_create_file);
    file.on('refresh:dependents', this.refresh_dependents);
    file.init();
    if (argv.watch && !this.is_under_inputs(filepath)) {
      this.watch_file(file.filepath);
    }
    return file;
  };

  Files.prototype.extract_file = function(filepath) {
    var index;
    index = _.findIndex(this.files, function(f) {
      return f.filepath === filepath;
    });
    return this.files.splice(index, 1)[0];
  };

  Files.prototype.is_under_inputs = function(filepath, consider_aliases) {
    var alias, dirpath, i, input, len, map, ref, ref1;
    input = true;
    ref = config.input;
    for (i = 0, len = ref.length; i < len; i++) {
      dirpath = ref[i];
      input && (input = filepath.indexOf(dirpath) === 0);
    }
    if (consider_aliases) {
      alias = true;
      ref1 = config.alias;
      for (map in ref1) {
        dirpath = ref1[map];
        dirpath = upath.join(dirs.pwd, dirpath);
        alias && (alias = filepath.indexOf(dirpath) === 0);
      }
    }
    return input || alias;
  };

  Files.prototype.bulk_create_file = function(deps) {
    var dep, i, len, results;
    results = [];
    for (i = 0, len = deps.length; i < len; i++) {
      dep = deps[i];
      results.push(this.create_file(dep));
    }
    return results;
  };

  Files.prototype.refresh_dependents = function(dependents) {
    var dependent, file, i, len, results;
    results = [];
    for (i = 0, len = dependents.length; i < len; i++) {
      dependent = dependents[i];
      file = _.find(this.files, {
        filepath: dependent.filepath
      });
      if (file != null) {
        results.push(file.refresh());
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  Files.prototype.watch_file = function(filepath) {
    var dir, watched, watcher;
    dir = path.dirname(filepath);
    watched = _.find(this.watchers, {
      root: dir
    });
    if (watched == null) {
      this.watchers.push(watcher = fsu.watch(dir));
      watcher.on('create', (function(_this) {
        return function(file) {
          return _this.onfschange('create', file);
        };
      })(this));
      watcher.on('change', (function(_this) {
        return function(file) {
          return _this.onfschange('change', file);
        };
      })(this));
      return watcher.on('delete', (function(_this) {
        return function(file) {
          return _this.onfschange('delete', file);
        };
      })(this));
    }
  };

  Files.prototype.watch_inputs = function() {
    var dirpath, i, len, ref, watched, watcher;
    ref = config.input;
    for (i = 0, len = ref.length; i < len; i++) {
      dirpath = ref[i];
      watched = _.find(this.watchers, {
        root: dirpath
      });
      if (watched == null) {
        this.watchers.push(watcher = fsu.watch(dirpath, exts));
        watcher.on('create', (function(_this) {
          return function(file) {
            return _this.onfschange('create', file);
          };
        })(this));
        watcher.on('change', (function(_this) {
          return function(file) {
            return _this.onfschange('change', file);
          };
        })(this));
        watcher.on('delete', (function(_this) {
          return function(file) {
            return _this.onfschange('delete', file);
          };
        })(this));
      }
    }
    return null;
  };

  Files.prototype.close_watchers = function() {
    var i, len, ref, results, watcher;
    ref = this.watchers;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      watcher = ref[i];
      results.push(watcher.close());
    }
    return results;
  };

  Files.prototype.onfschange = function(action, file) {
    var dep, depath, depname, dname, dpath, f, found, i, j, k, len, len1, len2, location, ref, ref1, ref2, ref3, ref4, ref5, type;
    location = file.location, type = file.type;
    if (type === "dir" && action === "create") {
      return;
    }
    if (type === "dir" && action === "delete") {
      return;
    }
    switch (action) {
      case "create":
        file = this.create_file(location);
        log_created(location);
        return this.compile(file);
      case "delete":
        log_deleted(location);
        file = this.extract_file(location);
        ref = file.dependencies;
        for (depname in ref) {
          depath = ref[depname];
          if (this.is_under_inputs(depath, true)) {
            continue;
          }
          found = 0;
          ref1 = this.files;
          for (i = 0, len = ref1.length; i < len; i++) {
            f = ref1[i];
            ref2 = f.dependencies;
            for (dname in ref2) {
              dpath = ref2[dname];
              if (dpath === depath) {
                found++;
              }
            }
          }
          if (!found) {
            this.extract_file(depath);
          }
        }
        if (file.is_partial) {
          ref3 = file.dependents;
          for (j = 0, len1 = ref3.length; j < len1; j++) {
            dep = ref3[j];
            _.find(this.files, {
              filepath: dep.filepath
            }).refresh();
          }
        } else {
          ref4 = this.files;
          for (k = 0, len2 = ref4.length; k < len2; k++) {
            f = ref4[k];
            ref5 = f.dependencies;
            for (dname in ref5) {
              dpath = ref5[dname];
              if (dpath === file.filepath) {
                f.refresh();
              }
            }
          }
        }
        return this.compile(file);
      case "change":
        file = _.find(this.files, {
          filepath: location
        });
        log_changed(location);
        file.refresh();
        return this.compile(file);
    }
  };

  Files.prototype.compile = function(file) {
    switch (file.output) {
      case 'js':
        return compiler.build_js(true);
      case 'css':
        return compiler.build_css(true);
    }
  };

  return Files;

})());

//# sourceMappingURL=files.js.map
