// Generated by CoffeeScript 1.10.0
var app, argv, config, connect, debug, dirs, error, fs, info, io, log, path, ref, refresher, sourcemaps, upath, warn;

path = require('path');

upath = require('upath');

fs = require('fs');

connect = require('connect');

io = require('socket.io');

dirs = require('../utils/dirs');

config = require('../utils/config');

sourcemaps = require('../utils/sourcemaps');

argv = require('../cli').argv;

ref = require('../utils/logger')('core/server'), error = ref.error, warn = ref.warn, info = ref.info, debug = ref.debug, log = ref.log;

app = null;

refresher = null;

module.exports = function() {
  var address, index, port, ref1, root;
  ref1 = config.server, root = ref1.root, port = ref1.port;
  index = upath.join(root, 'index.html');
  app = connect().use(connect["static"](root)).use(function(req, res) {
    if (~(req.url.indexOf('.'))) {
      res.statusCode = 404;
      return res.end('File not found: ' + req.url);
    } else {
      return res.end(fs.readFileSync(index, 'utf-8'));
    }
  }).listen(port);
  address = 'http://localhost:' + port;
  log("♫  " + address);
  if (!argv.r) {
    refresher = io.listen(53211, {
      'log level': 1
    });
  }
  return module.exports;
};

module.exports.close = function() {
  if (app != null) {
    app.close();
  }
  return refresher != null ? refresher.server.close() : void 0;
};

module.exports.reload = function(type) {
  var css_output;
  if (refresher == null) {
    return;
  }
  css_output = path.basename(config.output.css);
  return refresher.sockets.emit('refresh', {
    type: type,
    css_output: css_output
  });
};

//# sourceMappingURL=server.js.map
