// Generated by CoffeeScript 1.10.0
var app, argv, config, debug, dirs, error, finalhandler, fs, http, info, io, log, path, ref, refresher, server, servestatic, sourcemaps, upath, warn;

path = require('path');

upath = require('upath');

fs = require('fs');

http = require('http');

finalhandler = require('finalhandler');

servestatic = require('serve-static');

io = require('socket.io');

dirs = require('../utils/dirs');

config = require('../utils/config');

sourcemaps = require('../utils/sourcemaps');

argv = require('../cli').argv;

ref = require('../utils/logger')('core/server'), error = ref.error, warn = ref.warn, info = ref.info, debug = ref.debug, log = ref.log;

app = null;

server = null;

refresher = null;

module.exports = function() {
  var address, index, port, ref1, root, serve;
  ref1 = config.server, root = ref1.root, port = ref1.port;
  index = upath.join(root, 'index.html');
  serve = servestatic(root);
  server = http.createServer(function(req, res) {
    var done;
    done = finalhandler(req, res);
    return serve(req, res, done);
  });
  server.listen(port);
  address = 'http://localhost:' + port;
  log("♫  " + address);
  if (!argv.r) {
    refresher = new io(53211, {
      'log level': 1
    });
  }
  return module.exports;
};

module.exports.close = function() {
  if (server != null) {
    server.close();
  }
  return refresher != null ? refresher.httpServer.close() : void 0;
};

module.exports.reload = function(type) {
  var css_output;
  if (refresher == null) {
    return;
  }
  css_output = path.basename(config.output.css);
  return refresher.sockets.emit('refresh', {
    type: type,
    css_output: css_output
  });
};

//# sourceMappingURL=server.js.map
